# Generated by Django 3.1.4 on 2021-02-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='admitDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='admitDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='releaseDate',
            field=models.DateTimeField(),
        ),
    ]
